-- Silver layer: Clean and type call_events records

SELECT
  CAST(rec_id AS BIGINT) AS rec_id,
  CAST(customer_key AS STRING) AS customer_key,
  CAST(call_id AS DECIMAL(19,0)) AS call_id,
  CAST(call_sequence AS INT) AS call_sequence,
  CAST(media_type_id AS INT) AS media_type_id,
  CAST(dte_start AS TIMESTAMP) AS dte_start,
  CAST(duration_tot_sec AS INT) AS duration_tot_sec,
  CAST(duration_speak_sec AS INT) AS duration_speak_sec,
  CAST(dte_speak_start AS TIMESTAMP) AS dte_speak_start,
  CAST(source AS STRING) AS source,
  CAST(destination AS STRING) AS destination,
  CAST(additional_source AS STRING) AS additional_source,
  CAST(redirect_source AS STRING) AS redirect_source,
  CAST(service_num AS STRING) AS service_num,
  CAST(queue_key AS STRING) AS queue_key,
  CAST(menue_key AS STRING) AS menue_key,
  CAST(menue_choice AS STRING) AS menue_choice,
  CAST(agent_id AS INT) AS agent_id,
  CAST(event_type AS STRING) AS event_type,
  CAST(result_code AS STRING) AS result_code,
  CAST(answered AS BOOLEAN) AS answered,
  CAST(ciq AS STRING) AS ciq,
  CAST(call_transfer AS BOOLEAN) AS call_transfer,
  CAST(wrap_up_sec AS INT) AS wrap_up_sec,
  CAST(alert_ms AS INT) AS alert_ms,
  CAST(setup_ms AS INT) AS setup_ms,
  CAST(block_duration_sec AS INT) AS block_duration_sec,
  CAST(internal_iq_session_id AS STRING) AS internal_iq_session_id,
  CAST(internal_odr_id AS BIGINT) AS internal_odr_id,
  CAST(dte_updated AS TIMESTAMP) AS dte_updated,
  CAST(sla AS INT) AS sla,
  CAST(alt_sla AS INT) AS alt_sla,
  CAST(dte_scheduled_callback AS TIMESTAMP) AS dte_scheduled_callback,
  CAST(result_response AS INT) AS result_response,
  CAST(request_id AS BIGINT) AS request_id,
  CAST(hold AS INT) AS hold,
  CAST(consult AS INT) AS consult,
  CAST(leg_type AS STRING) AS leg_type,
  CAST(originating AS STRING) AS originating,
  CAST(add_originating AS STRING) AS add_originating,
  CAST(caller_on_hold_sec AS INT) AS caller_on_hold_sec
FROM bronze.puzzel_call_events
