SELECT
    CAST(case_id AS BIGINT)                     AS case_id,
    CAST(verification_code AS STRING)           AS verification_code,
    CAST(correlation_id AS STRING)              AS correlation_id,
    CAST(pcn AS STRING)                         AS pcn,
    CAST(vehicle_registration AS STRING)        AS vehicle_registration,
    CAST(submitted_on_behalf AS BIGINT)         AS submitted_on_behalf,
    CAST(operator_code AS STRING)               AS operator_code,
    CAST(submission_date AS TIMESTAMP)          AS submission_date,
    CAST(case_condition AS STRING)              AS case_condition,
    CAST(status AS STRING)                      AS status,
    CAST(assessor_id AS BIGINT)                 AS assessor_id,
    CAST(decision AS STRING)                    AS decision,
    CAST(decision_date AS TIMESTAMP)            AS decision_date,
    CAST(withdrawn_by AS STRING)                AS withdrawn_by,
    CAST(withdrawal_reasons AS STRING)          AS withdrawal_reasons,
    CAST(withdrawal_date AS TIMESTAMP)          AS withdrawal_date,
    CAST(custom_field_1 AS STRING)              AS custom_field_1,
    CAST(custom_field_2 AS STRING)              AS custom_field_2,
    CAST(primary_contact AS BIGINT)             AS primary_contact,
    CAST(secondary_contact AS BIGINT)           AS secondary_contact,
    CAST(summary_operator AS STRING)            AS summary_operator,
    CAST(summary_appellant AS STRING)           AS summary_appellant,
    CAST(summary_reasons AS STRING)             AS summary_reasons,
    CAST(case_source AS STRING)                 AS case_source,
    CAST(state_change_date AS TIMESTAMP)        AS state_change_date,
    CAST(version AS BIGINT)                     AS version,
    CAST(operator_evidence_excluded AS BIGINT)  AS operator_evidence_excluded,
    CAST(status_reason AS STRING)               AS status_reason,
    CAST(withdrawal_reason_code AS STRING)      AS withdrawal_reason_code
FROM
    bronze.popla_appellant_cases
