-- Silver transformation for additional infos

SELECT DISTINCT
  CAST(id AS BIGINT) AS id,
  CAST(hear_from AS STRING) AS hear_from,
  CAST(communication_needs AS BOOLEAN) AS communication_needs,
  CAST(survey AS BOOLEAN) AS survey,
  CAST(communication AS STRING) AS communication,
  CAST(anything_else AS STRING) AS anything_else,
  CAST(complaint_id AS BIGINT) AS complaint_id,
  CAST(created_at AS TIMESTAMP) AS created_at,
  CAST(updated_at AS TIMESTAMP) AS updated_at,
  CAST(has_smart_meter AS BOOLEAN) AS has_smart_meter,
  CAST(consumers_company_response_id AS BIGINT) AS consumers_company_response_id,
  CAST(consumers_response_at AS DATE) AS consumers_response_at,
  CAST(consumers_first_complained_at AS DATE) AS consumers_first_complained_at,
  CAST(companys_company_response_id AS BIGINT) AS companys_company_response_id,
  CASE WHEN companys_response_at >= '1900-01-01' THEN CAST(companys_response_at AS DATE) ELSE NULL END AS companys_response_at,
  CAST(companys_response_at AS STRING) AS companys_response_at_raw,
  CASE WHEN companys_referral_notification_at >= '1900-01-01' THEN CAST(companys_referral_notification_at AS DATE) ELSE NULL END AS companys_referral_notification_at,
  CAST(companys_referral_notification_at AS STRING) AS companys_referral_notification_at_raw,
  CAST(referral_evidence_included AS BOOLEAN) AS referral_evidence_included,
  CAST(accurately_recorded AS BOOLEAN) AS accurately_recorded,
  CAST(communications_limit AS BOOLEAN) AS communications_limit,
  CAST(energy_limit AS BOOLEAN) AS energy_limit,
  CAST(turnover_limit AS BOOLEAN) AS turnover_limit,
  CAST(sf_evidence_step_state AS STRING) AS sf_evidence_step_state,
  CAST(challenge_resolution_reason AS STRING) AS challenge_resolution_reason,
  CAST(hear_from_other_text AS STRING) AS hear_from_other_text,
  CAST(site_issue_id AS BIGINT) AS site_issue_id,
  CAST(supplier_business_categorisation AS STRING) AS supplier_business_categorisation,
  CAST(number_of_employees AS INT) AS number_of_employees,
  CAST(balance_or_turnover AS INT) AS balance_or_turnover,
  CAST(balance_turnover_value AS INT) AS balance_turnover_value,
  CAST(electricity_usage AS INT) AS electricity_usage,
  CAST(gas_usage AS INT) AS gas_usage,
  CAST(eligibility_date AS DATE) AS eligibility_date,
  CAST(review_eligibility_period_seconds AS INT) AS review_eligibility_period_seconds,
  CAST(company_sites_id AS BIGINT) AS company_sites_id
FROM bronze.cms_additional_infos
